buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '4.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'

version = '1.0'
group = 'client'
archivesBaseName = 'VilonExtended'

sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    mappings channel: 'official', version: '1.16.5'
    runs {
        client {
            property 'forge.logging.mojang_level', 'debug'
            mods {
                vilonextended {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    implementation fg.deobf('net.minecraftforge:forge:1.16.5-36.2.34')
}

jar {
    manifest {
        attributes([
            "Specification-Title": "VilonExtended",
            "Specification-Vendor": "client",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": project.version,
            "Implementation-Vendor": "client",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
